In [34]:
import pandas as pd
import numpy as np

ser = pd.Series([10,20,30])
df = pd.DataFrame([[10,"a",True],
                 [20,"b",False],
                 [30,"c",False],
                 [40,"d",True]])

df = pd.DataFrame(np.arange(100).reshape((25,4)))
df.head()


0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [40]:
##次元数の変換
##テストデータc1
c1 = np.array([1,2,3,4,5,6])

##次元数変換 引数はタプル
c2 = c1.reshape((2,3))

##２次元配列のインデックス
##print(c2)
##print (c2[1,0])

##２次元配列のスライス
print(c2)
print (c2[0,:])

print (c2[0,1:])
c2[0,1:] = 0
print (c2[0,1:])

print (c2)
print (c2[:,1])


##メモ
##次元数変換は要素数が大事
##4 x 2 のとき
c1 = np.array([1,2,3,4,5,6,7,8])
c2 = c1.reshape((4,2))


##1次元配列に変換 コピーしない
c3 = c2.ravel()
##1次元配列に変換 コピー
c4 = c2.flatten()

##深いコピーについて


[[1 2 3]
 [4 5 6]]
[1 2 3]
[2 3]
[0 0]
[[1 0 0]
 [4 5 6]]
[0 5]


In [1]:
import numpy as np

##データ型を指定してnumpyを使う
a = np.array([1,2,3],dtype=np.int16)

##中身の表示
print(a)

##データが型を調べる
type (a)

##次元数を調べる
a.shape

##データ型を表示する
a.dtype

##numpy にも インデックスとスライスがある
print (a[0])
print (a[1:])

##異なる表現で同じスライスを表現する
print (a[:-1])
print (a[:2])



[1 2 3]
1
[2 3]
[1 2]
[1 2]
